In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, accuracy_score

In [23]:

!pip install tensorflow[and-cuda]


ERROR: Cannot install tensorflow[and-cuda]==2.16.1, tensorflow[and-cuda]==2.16.2, tensorflow[and-cuda]==2.17.0, tensorflow[and-cuda]==2.17.1, tensorflow[and-cuda]==2.18.0, tensorflow[and-cuda]==2.18.1, tensorflow[and-cuda]==2.19.0, tensorflow[and-cuda]==2.19.1 and tensorflow[and-cuda]==2.20.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts



INFO: pip is looking at multiple versions of tensorflow[and-cuda] to determine which version is compatible with other requirements. This could take a while.
INFO: pip is still looking at multiple versions of tensorflow[and-cuda] to determine which version is compatible with other requirements. This could take a while.

The conflict is caused by:
    tensorflow[and-cuda] 2.20.0 depends on nvidia-nccl-cu12<3.0 and >=2.25.1; extra == "and-cuda"
    tensorflow[and-cuda] 2.19.1 depends on nvidia-nccl-cu12==2.23.4; extra == "and-cuda"
    tensorflow[and-cuda] 2.19.0 depends on nvidia-nccl-cu12==2.23.4; extra == "and-cuda"
    tensorflow[and-cuda] 2.18.1 depends on nvidia-nccl-cu12==2.21.5; extra == "and-cuda"
    tensorflow[and-cuda] 2.18.0 depends on nvidia-nccl-cu12==2.21.5; extra == "and-cuda"
    tensorflow[and-cuda] 2.17.1 depends on nvidia-nccl-cu12==2.19.3; extra == "and-cuda"
    tensorflow[and-cuda] 2.17.0 depends on nvidia-nccl-cu12==2.19.3; extra == "and-cuda"
    tensorflow[and-

In [25]:
!pip install --upgrade pip setuptools wheel
!pip install --upgrade tensorflow[and-cuda]


  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 2.8 MB/s eta 0:00:01
   ----------------------------- ---------- 1.3/1.8 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 3.5 MB/s eta 0:00:00
Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)


ERROR: To modify pip, please run the following command:
C:\Users\acer\anaconda3\python.exe -m pip install --upgrade pip setuptools wheel


  Using cached nvidia_cublas_cu12-12.9.1.4-py3-none-win_amd64.whl.metadata (1.7 kB)
  Using cached nvidia_cuda_cupti_cu12-12.9.79-py3-none-win_amd64.whl.metadata (1.8 kB)
  Using cached nvidia_cuda_nvcc_cu12-12.9.86-py3-none-win_amd64.whl.metadata (1.7 kB)
  Using cached nvidia_cuda_nvrtc_cu12-12.9.86-py3-none-win_amd64.whl.metadata (1.7 kB)
  Using cached nvidia_cuda_runtime_cu12-12.9.79-py3-none-win_amd64.whl.metadata (1.7 kB)
  Using cached nvidia_cudnn_cu12-9.14.0.64-py3-none-win_amd64.whl.metadata (1.8 kB)
  Using cached nvidia_cufft_cu12-11.4.1.4-py3-none-win_amd64.whl.metadata (1.8 kB)
  Using cached nvidia_curand_cu12-10.3.10.19-py3-none-win_amd64.whl.metadata (1.7 kB)
  Using cached nvidia_cusolver_cu12-11.7.5.82-py3-none-win_amd64.whl.metadata (1.9 kB)
  Using cached nvidia_cusparse_cu12-12.5.10.65-py3-none-win_amd64.whl.metadata (1.8 kB)
INFO: pip is looking at multiple versions of tensorflow[and-cuda] to determine which version is compatible with other requirements. This co

ERROR: Cannot install tensorflow[and-cuda]==2.16.1, tensorflow[and-cuda]==2.16.2, tensorflow[and-cuda]==2.17.0, tensorflow[and-cuda]==2.17.1, tensorflow[and-cuda]==2.18.0, tensorflow[and-cuda]==2.18.1, tensorflow[and-cuda]==2.19.0, tensorflow[and-cuda]==2.19.1 and tensorflow[and-cuda]==2.20.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts


In [26]:
import tensorflow as tf
from tensorflow import keras
import time

# Simple computation to check GPU usage
with tf.device('/GPU:0'):
    start = time.time()
    a = tf.random.normal([10000, 10000])
    b = tf.random.normal([10000, 10000])
    c = tf.matmul(a, b)
    print("GPU computation time:", time.time() - start, "seconds")


GPU computation time: 16.70322012901306 seconds


In [ ]:
# pip install tensorflow ignore if already installed
!pip install tensorflow


In [49]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [50]:
dataset = pd.read_csv('Churn_Modelling.csv', index_col = 'RowNumber')

In [51]:
dataset.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
RowNumber                                                                     
1            15634602  Hargrave          619    France  Female   42       2   
2            15647311      Hill          608     Spain  Female   41       1   
3            15619304      Onio          502    France  Female   42       8   
4            15701354      Boni          699    France  Female   39       1   
5            15737888  Mitchell          850     Spain  Female   43       2   

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber                                                        
1               0.00              1          1               1   
2           83807.86              1          0               1   
3          159660.80              3          1               0   
4               0.00              2          0               0   
5          125510.82              1          1               1   

           EstimatedSalary  Exited  
RowNumber                           
1                101348.88       1  
2                112542.58       0  
3                113931.57       1  
4                 93826.63       0  
5                 79084.10       0

In [52]:
# Features and target
X = dataset.iloc[:, 2:12]
X  # drop CustomerId and Surname

CreditScore Geography  Gender  Age  Tenure    Balance  \
RowNumber                                                          
1                  619    France  Female   42       2       0.00   
2                  608     Spain  Female   41       1   83807.86   
3                  502    France  Female   42       8  159660.80   
4                  699    France  Female   39       1       0.00   
5                  850     Spain  Female   43       2  125510.82   
...                ...       ...     ...  ...     ...        ...   
9996               771    France    Male   39       5       0.00   
9997               516    France    Male   35      10   57369.61   
9998               709    France  Female   36       7       0.00   
9999               772   Germany    Male   42       3   75075.31   
10000              792    France  Female   28       4  130142.79   

           NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
RowNumber                                                             
1                      1          1               1        101348.88  
2                      1          0               1        112542.58  
3                      3          1               0        113931.57  
4                      2          0               0         93826.63  
5                      1          1               1         79084.10  
...                  ...        ...             ...              ...  
9996                   2          1               0         96270.64  
9997                   1          1               1        101699.77  
9998                   1          0               1         42085.58  
9999                   2          1               0         92888.52  
10000                  1          1               0         38190.78  

[10000 rows x 10 columns]

In [53]:
# Features and target
Y = dataset.iloc[:, 12].values  # Churn column
Y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [54]:
# Pipeline: One-hot encode categorical and scale
pipeline = Pipeline([
    ('preprocess', ColumnTransformer(
        transformers=[
            ('gender', OneHotEncoder(drop='first'), ['Gender']),
            ('geo', OneHotEncoder(drop='first'), ['Geography'])
        ],
        remainder='passthrough'
    )),
    ('scaler', StandardScaler())
])

In [55]:
#Standardize the features
X = pipeline.fit_transform(X)

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [57]:
# Build ANN
classifier = Sequential()
classifier.add(Dense(6, activation='relu', input_shape=(X_train.shape[1],)))
classifier.add(Dropout(0.1))
classifier.add(Dense(6, activation='relu'))
classifier.add(Dropout(0.1))
classifier.add(Dense(1, activation='sigmoid'))

C:\Users\acer\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [58]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [59]:
# Train ANN
history = classifier.fit(X_train, y_train, batch_size=32, epochs=100, validation_split=0.1, verbose=2)

Epoch 1/100
225/225 - 4s - 16ms/step - accuracy: 0.7272 - loss: 0.6086 - val_accuracy: 0.7875 - val_loss: 0.5026
Epoch 2/100
225/225 - 1s - 4ms/step - accuracy: 0.7919 - loss: 0.5038 - val_accuracy: 0.7925 - val_loss: 0.4621
Epoch 3/100
225/225 - 1s - 6ms/step - accuracy: 0.7968 - loss: 0.4785 - val_accuracy: 0.7950 - val_loss: 0.4464
Epoch 4/100
225/225 - 1s - 4ms/step - accuracy: 0.7964 - loss: 0.4644 - val_accuracy: 0.7950 - val_loss: 0.4371
Epoch 5/100
225/225 - 1s - 4ms/step - accuracy: 0.7965 - loss: 0.4552 - val_accuracy: 0.7962 - val_loss: 0.4303
Epoch 6/100
225/225 - 1s - 6ms/step - accuracy: 0.7978 - loss: 0.4499 - val_accuracy: 0.7962 - val_loss: 0.4249
Epoch 7/100
225/225 - 1s - 6ms/step - accuracy: 0.8012 - loss: 0.4383 - val_accuracy: 0.7975 - val_loss: 0.4161
Epoch 8/100
225/225 - 1s - 4ms/step - accuracy: 0.8083 - loss: 0.4305 - val_accuracy: 0.8075 - val_loss: 0.4056
Epoch 9/100
225/225 - 1s - 6ms/step - accuracy: 0.8156 - loss: 0.4174 - val_accuracy: 0.8150 - val_loss

In [60]:
# Predict
y_pred = (classifier.predict(X_test) > 0.5).astype(int)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


In [61]:
y_pred = classifier.predict(X_test)
print(y_pred[:5])

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[0.24285598]
 [0.29548812]
 [0.16572848]
 [0.05861929]
 [0.10513144]]


In [62]:
#Let us use confusion matrix with cutoff value as 0.5
y_pred = (y_pred > 0.5).astype(int)
print(y_pred[:5])

[[0]
 [0]
 [0]
 [0]
 [0]]


In [63]:
#Making the Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[1541   54]
 [ 212  193]]


In [64]:
#Accuracy of our NN
print(((cm[0][0] + cm[1][1])* 100) / len(y_test), '% of data was classified correctly')

86.7 % of data was classified correctly
